export const restaurants = [
  { id: 1, name: 'Hioki Sushi', type: 'Japonesa', rating: 4.9, featured: true, image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=900&q=85', hero: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1600&q=85', description: 'Peça já o melhor da culinária japonesa no conforto da sua casa! Sushis frescos, sashimis e pratos quentes preparados com ingredientes selecionados.' },
  { id: 2, name: 'La Dolce Vita Trattoria', type: 'Italiana', rating: 4.6, featured: true, image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=85', hero: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1600&q=85', description: 'A La Dolce Vita traz a autêntica cozinha italiana: massas artesanais, pizzas de longa fermentação e molhos preparados lentamente.' },
  { id: 3, name: 'Bella Napoli', type: 'Italiana', rating: 4.7, image: 'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=85', hero: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1600&q=85', description: 'Na Bella Napoli, pizzas artesanais e receitas napolitanas ganham vida com ingredientes frescos e muito sabor.' },
  { id: 4, name: 'Sakura House', type: 'Japonesa', rating: 4.8, image: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=900&q=85', hero: 'https://images.unsplash.com/photo-1617196034183-421b4917c92d?auto=format&fit=crop&w=1600&q=85', description: 'A Sakura House combina tradição japonesa, peixes frescos e apresentações delicadas em cada pedido.' },
  { id: 5, name: 'Nonna Mia', type: 'Italiana', rating: 4.8, image: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=900&q=85', hero: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1600&q=85', description: 'Receitas de família, massas frescas e molhos feitos com calma: a verdadeira cozinha da nonna na sua casa.' },
  { id: 6, name: 'Kyoto Garden', type: 'Japonesa', rating: 4.7, image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=900&q=85', hero: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=1600&q=85', description: 'O Kyoto Garden oferece combinados, sashimis e pratos autorais com ingredientes selecionados diariamente.' },
]

export const menus = {
  Japonesa: [
    {
      id: 101,
      name: 'Uramaki de Salmão',
      image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=700&q=85',
      short: 'Uramakis de salmão com cream cheese e cebolinha fresca.',
      description: 'Rolls de arroz japonês recheados com salmão e cream cheese, cobertos com salmão fresco e finalizados com cebolinha.',
      price: '72,90',
    },
    {
      id: 102,
      name: 'Barco Japonês',
      image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=700&q=85',
      short: 'Seleção completa de sushis, rolls, niguiris e sashimis.',
      description: 'Um barco generoso com variedades de sushi, niguiris de salmão e atum, rolls crocantes e opções com avocado.',
      price: '64,90',
    },
    {
      id: 103,
      name: 'Hot Filadélfia',
      image: 'https://images.unsplash.com/photo-1617196034183-421b4917c92d?auto=format&fit=crop&w=700&q=85',
      short: 'Roll empanado de salmão e cream cheese, servido crocante.',
      description: 'Sushi empanado e dourado com recheio de salmão e cream cheese, preparado na hora e servido ainda crocante.',
      price: '32,90',
    },
    {
      id: 104,
      name: 'Seleção do Chef',
      image: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=700&q=85',
      short: 'Combinado de sushis de salmão, hossomakis e rolls variados.',
      description: 'Seleção colorida do chef com sushis de salmão, pequenos hossomakis, avocado e acompanhamentos japoneses.',
      price: '39,90',
    },
    {
      id: 105,
      name: 'Uramaki Salmão e Avocado',
      image: 'https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?auto=format&fit=crop&w=700&q=85',
      short: 'Roll de salmão e avocado coberto com salmão e ovas.',
      description: 'Uramaki recheado com salmão e avocado, coberto com lâminas de salmão fresco e ovas para uma finalização especial.',
      price: '42,90',
    },
    {
      id: 106,
      name: 'Bowl de Salmão Grelhado',
      image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=700&q=85',
      short: 'Salmão grelhado com arroz, vagem, tomates e ervas frescas.',
      description: 'Bowl equilibrado com filé de salmão grelhado, arroz, vagem, tomates coloridos, sementes e ervas frescas.',
      price: '49,90',
    },
  ],
  Italiana: [
    {
      id: 201,
      name: 'Pizza Marguerita',
      image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=700&q=85',
      short: 'Molho de tomate, muçarela, manjericão fresco e azeite.',
      description: 'Pizza italiana de massa fina e crocante, molho de tomate fresco, muçarela de alta qualidade, manjericão e azeite.',
      price: '60,90',
    },
    {
      id: 202,
      name: 'Pizza Napolitana',
      image: 'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=700&q=85',
      short: 'Molho de tomate, muçarela fresca, manjericão e borda aerada.',
      description: 'Pizza napolitana assada em forno a lenha, com massa de longa fermentação, tomate, muçarela e manjericão.',
      price: '66,90',
    },
    {
      id: 203,
      name: 'Pizza de Burrata e Rúcula',
      image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=700&q=85',
      short: 'Molho de tomate, queijo cremoso, burrata e rúcula fresca.',
      description: 'Massa artesanal coberta com molho de tomate, queijo, folhas de rúcula e porções generosas de burrata cremosa.',
      price: '68,90',
    },
    {
      id: 204,
      name: 'Farfalle ao Pesto',
      image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=700&q=85',
      short: 'Massa farfalle com pesto de manjericão e tomates-cereja.',
      description: 'Farfalle al dente envolvido em pesto de manjericão, acompanhado de tomates-cereja frescos e folhas verdes.',
      price: '52,90',
    },
    {
      id: 205,
      name: 'Penne à Bolonhesa',
      image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=700&q=85',
      short: 'Penne com ragu de carne, molho de tomate e parmesão.',
      description: 'Penne al dente servido com ragu bovino e molho de tomate encorpado, finalizado com parmesão e pimenta-do-reino.',
      price: '58,90',
    },
    {
      id: 206,
      name: 'Lasanha à Bolonhesa',
      image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=700&q=85',
      short: 'Camadas de massa, ragu, molho bechamel e parmesão.',
      description: 'Lasanha clássica com massa artesanal, ragu bovino cozido lentamente, bechamel e queijo gratinado.',
      price: '62,90',
    },
  ],
}
